service:
  port: 8001

# mysql配置
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: dream-book
  engine: innodb
  max-idle-conns: 10
  max-open-conns: 100

# redis配置
redis:
  database: 0
  addr: localhost:6379
# 日志配置
log:
  level: debug
  path: ./logs
  filename: "app.log"
